### ISSUE TITLE
Embedded attachments

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/com.woltlab.wcf.exporter#16]
Wordpress allows you to embed attachments in posts, which have been uploaded in another post. These attachments referencing the post, in which they've been uploaded (via `post_parent`).

The problem is, that WP embeds these attachments as HTML code (e.g. img-tags) directly. So, files are always linked to their original location, which is the upload directory of WP.

So, after a successful import, you need to iterate through all imported blog posts and replace the original attachment references with the local attachment reference. Otherwise, the whole WP import process makes not much sense, because as soon, as you delete your Wordpress blog, all embedded attachments are no longer accessible.

**Comment by lycra** [comment]
Will there be any update for the WCF 2.2 importer?
