### ISSUE TITLE
IPB 3.4 - Archived Threads

### ISSUE THREAD

**Issue by DragonGun** [WoltLab/com.woltlab.wcf.exporter#18]
IPB has a function to set Threads as archived.

Archived Threads are partially "ignored" by the actual importer.
The thread itself get's imported, but will be empty in the Forum itself, no posts at all.

**Comment by TimWolla** [comment]
@DragonGun Do you expect the threads to be imported or ignored?

**Comment by DragonGun** [comment]
Either they should be imported (with the posts) or the threads should be removed.
My personal wish would be, that they will get imported as well, since WBB/WCF doesn't has an archive function.
