### ISSUE TITLE
Make adjustments for WCF#2957

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/com.woltlab.wcf.exporter#35]
see WoltLab/WCF#2957

**Comment by dtdesign** [comment]
@TimWolla What kind of adjustements, it appears to me that this has already been implemented in the inherited method and thus should work out of the box?

**Comment by TimWolla** [comment]
I concede that I could've been more clear: “Adjustments” = “Remove the redundant processing from the exporters to improve performance and clarify the code”
