### ISSUE TITLE
Display target app for exporters

### ISSUE THREAD

**Issue by mutec** [WoltLab/com.woltlab.wcf.exporter#39]
Since there are exporters that might be able to import/export from the same source-software but into different apps.
So it might be good to change the select-list to the following example:
![image](https://user-images.githubusercontent.com/1749344/62835856-452bf580-bc5d-11e9-970b-bdab50cf1e3e.png)

**Comment by dtdesign** [comment]
You can already include those in the name of the importer if you feel the need for it. For the majority this introduces a lot of visual clutter with an unclear benefit, I can't recall any complaints in that direction.
