### ISSUE TITLE
Migration from IPS to WoltLab

### ISSUE THREAD

**Issue by eveneme** [WoltLab/com.woltlab.wcf.exporter#81]
Due to the dramatic changes in prices and licensing policies of IPS, many people will be looking for an alternative to switch to another platform. I am on this path myself and want to migrate my forum from IPS to WoltLab. However, I would like the migration to be more comprehensive than it currently is. I want more information to be transferred from the old forum to the new one. Therefore, I am suggesting an expansion of the WoltLab exporter for IPS. Please consider and review my request as I plan to migrate next year (and I am probably not the only one, as many people are dissatisfied).

**Comment by BurntimeX** [comment]
What exactly are you currently missing with the IPS importer?

Our import system is essentially based on importing the standard data that all forum software have in common. Importing special data from individual forum software is usually relatively difficult and time-consuming.

**Comment by eveneme** [comment]
Thank you for the response. Could you please tell me what exactly the importer currently includes? Unfortunately, I can't find the documentation. Regards

**Comment by dtdesign** [comment]
@eveneme If you have some spare time, we would greatly appreciate if you could tell us what you are missing and feel is crucial for a successful migration?

**Comment by eveneme** [comment]
Sorry for the late response. I will describe everything tomorrow.

**Comment by BurntimeX** [comment]
> Will the link structure be preserved to avoid losing SEO positioning?

You can set up redirects for the old links, e.g. using mod_rewrite. See: https://manual.woltlab.com/en/migration-url-rewrites/

> Will all page titles and meta descriptions be retained?

Page titles and meta descriptions are generated on the basis of the thread title and the text and therefore remain largely unchanged.

> Will tags also be transferred?

Yes.

> Will passwords remain the same or will they need to be reset?

Passwords remain the same.

> Will user permissions and groups be fully preserved?

User groups are imported, but permissions are not. The reason for this is that these usually differ too much from one software to another and therefore cannot be imported in a useful way.

**Comment by eveneme** [comment]
@BurntimeX 

> You can set up redirects for the old links, e.g. using mod_rewrite. See: https://manual.woltlab.com/en/migration-url-rewrites/

I can't find it on this list: Invision Community

**Comment by BurntimeX** [comment]
These are basic examples that usually always have to be adapted individually, as the URL structure can be customized for each software.

We are happy to help with this as part of our ticket support.
