### ISSUE TITLE
VB5 [ thread_post ]

### ISSUE THREAD

**Issue by BliNeR-KeY** [WoltLab/com.woltlab.wcf.exporter#82]
hello i was Testing [WoltLab Suite Core 6.0.16]( https://www.woltlab.com/en/woltlab-suite-download/)

[According](https://manual.woltlab.com/en/migration-sources/#vbulletin)

I Try import my vBulletin 5.7.5 Patch Level 3 it no works.

- Forum Structure
- Threads and Posts 

i try via ACP ns php CLI.

Forum only 190k posts.

**Comment by dtdesign** [comment]
What do you mean, it does not work? Have you installed the forum app prior to attempting the import?

**Comment by BliNeR-KeY** [comment]
honestly i gived up. coz it no works. 

yes i installed from forum app. 

it no works on vbulletin. 
its so sad coz WoltLab are really good forum. and vbulletin are no working on plugins no more members dev.
old plugins and nothink compatile. only lost time . 
example no shoutbox old and not compatible. etc etc...
all vbulletin members are getting the way to run and emigrate in other forums. 

xenforo importer it works as well in vbulletin import everything.. but i dont like xenforo. 

i feel so sad why WoltLab no works a lot in inporter for old forums costumers like me since 2005 vbulletin are important no lost anthing.

**Comment by dtdesign** [comment]
That’s sad to hear but why didn’t you contact us through the [ticket support](https://www.woltlab.com/ticket-add/)? We’re happy to help any customer that experiences issues and if there is an issue with the importer we can resolve it.
